### ISSUE TITLE
Move to single branch

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc-client-docker#1]
Hi @adamradocz thanks again for this, its great to have! I have some minor comments after taking this for a spin, which I'm totally open to discussion on. I'll open them as separate issues here for organizational purposes. 

First, what if instead of 4 separate branches for the different Dockerfiles, we have 1 branch with four folders for each of the tags? Its just a bit clunky switching branches all the time, and its more difficult if you ever want to compare any of the four Dockerfiles against each other. You can still do the automated build correctly by just using the "Dockerfile Location" option.

**Comment by adamradocz** [comment]
I agree. It was just easier to me, because I had never worked with tags before.
Could you do the reorganizations?
BTW, we need only 3 tags, because the amd and opencl tags are the same.

**Comment by marius311** [comment]
> Could you do the reorganizations?

Sure, I'll have a go at it later today.

**Comment by adamradocz** [comment]
What do you think, should we emphasize the opencl tag, or use only the amd tag?

**Comment by marius311** [comment]
Yea, not sure. I'm tempted to go with `nvidia-cuda` and `opencl` as tag names, since that exactly matches the names of Debian packages. Thoughts?

**Comment by adamradocz** [comment]
Sounds right with me.

**Comment by marius311** [comment]
Closed by https://github.com/BOINC/boinc-client-docker/commit/0cf57a4148595c4e9313571b2a84e6cfe6657434

We need (and needed before anyway) some tweaking to do the autobuild right, because otherwise you weren't guaranteed to build `boinc/client:latest` before you built the nvidia/cuda version that depend on it.  The file in hooks/build should nominally fix that, but I need to test it still. We'll have to set up the autobuild via Docker Cloud instead of Docker Hub, but its a nicer newer thing anyway.

**Comment by marius311** [comment]
@davidpanderson @TheAspens I think I need to be part of the Github BOINC organization to correctly set up the Docker automated build. Could I be added? I don't need permissions on anything other than this repo.

**Comment by davidpanderson** [comment]
I invited you.
-- D

**Comment by marius311** [comment]
Thanks!

**Comment by marius311** [comment]
Actually, there may be one more thing needed. Under the BOINC organization settings, under Third Party Access, do you see anything related to "Docker Cloud Builder" and if so could you approve it? (if there's nothing like that, I'd be curious to know still)

**Comment by davidpanderson** [comment]
Marius:
Under Third Party Access it says
Third-party application access policy

Policy: *No restrictions*

All applications authorized by organization members have access to *BOINC*’s
data.

When authorized, applications can act on behalf of organization members.
Your access policy determines which applications can access data in your
organization. Read more about third-party access and organizations.
<https://help.github.com/articles/about-third-party-application-restrictions/>
