### ISSUE TITLE
How to install boinc_client Docker on Synology

### ISSUE THREAD

**Issue by francesco1119** [BOINC/boinc-client-docker#110]
I'm having an hard time trying to install [boinc_client Docker][1] on my Synology. 

After having downloaded the latest image through the Synology Docker I launch the image and I use the default setting `bridge`

[![enter image description here][2]][2]

I tune a bit the CPU and the Memory and I let all other settings as default: 

[![enter image description here][3]][3]

I keep the port as the default one: 

[![enter image description here][4]][4]

I set a folder in my volume: 

[![enter image description here][5]][5]

Now the container is created and it's up and running on my Synology at port `31416`

[![enter image description here][6]][6]

But if I try to connect to it:

    404 Not Found
    nginx

[![enter image description here][7]][7]

What am I doing wrong? 

On the official documentation is not written what is the default web page for the `boinc_client`. 

I believe the root cause is overall the network setup but I tried with or without `bridge`; I tried setting different port with HTTP/HTTPS; I also tried setting the host as the IP address of the Synology. Nothing seems working. 

  [1]: https://hub.docker.com/r/boinc/client#usage
  [2]: https://i.sstatic.net/7omjaOLe.png
  [3]: https://i.sstatic.net/84zQbGTK.png
  [4]: https://i.sstatic.net/3KUfD1gl.png
  [5]: https://i.sstatic.net/GP5rzuiQ.png
  [6]: https://i.sstatic.net/M6erxKKp.png
  [7]: https://i.sstatic.net/19Blpia3.png

**Comment by AenBleidd** [comment]
You need to use BOINC Manager to connect to your BOINC client inside docker container since BOINC Client doesn't provide any web interface

**Comment by francesco1119** [comment]
Thank you @AenBleidd .
Where can I download the BOINC Manager? Is that a Docker image too? 
Any documentation about how to manage a Client form the Manager?

**Comment by AenBleidd** [comment]
Hello Francesco,

You can download BOINC Manager with BOINC Client here:
https://boinc.berkeley.edu/download.php
Regarding the documentation, it's all here:
https://github.com/BOINC/boinc/wiki/User-manual

Best regards,
Vitalii Koshura


пн, 14 окт. 2024 г. в 22:06, Francesco Mantovani ***@***.***>:

**Comment by AenBleidd** [comment]
You can download BOINC Manager with BOINC Client here: https://boinc.berkeley.edu/download.php
Regarding the documentation, it's all here: https://github.com/BOINC/boinc/wiki/User-manual

**Comment by francesco1119** [comment]
I just want to write this down because there are so many people trying to archive this on a NAS. 

- BOINC Manager is for [Windows](https://boinc.berkeley.edu/download.php) or VirtualBox. 
- On a NAS you can install the BOINC client only with [Docker ](https://hub.docker.com/r/boinc/client)or through [apt-get](https://boinc.berkeley.edu/linux_install.php?os_num=5&build=stable) (skip the BOINC Manager in this case 
- In case you archive to install the BOINC Client on a NAS the BOINC client can be controlled either using [boinccmd](https://boinc.berkeley.edu/wiki/Boinccmd_tool), or using a [remote GUI](https://boinc.berkeley.edu/wiki/Controlling_BOINC_remotely).

Feature Request: It's a pity that there is no BOINC Manager on Docker with a web interface. That would be much easier and would add so many more users and calculation power to the projects.
