### ISSUE TITLE
Trigger autobuild when base repository updated

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc-client-docker#13]
Ubuntu is updated it's images, therefore the containers should be rebuilt. I manually rebuilt them, but it should be automatic.
On the Docker Hub you can set the base repository to trigger the autobuild, but I didn't find this option on the Docker Cloud.

@marius311 do you have any idea, how to do that?

**Comment by marius311** [comment]
Yea, unfortunately I don't see this feature either. Hopefully its added soon... https://forums.docker.com/t/how-to-link-parent-repositories-in-docker-cloud/35788

**Comment by adamradocz** [comment]
Base repositories:
- ubuntu/18.04
- intelopencl/intel-opencl
- nvidia/cuda:10.0-base-ubuntu18.04
