### ISSUE TITLE
Set Client Name

### ISSUE THREAD

**Issue by LiamAkkerman** [BOINC/boinc-client-docker#16]
Would it be possible to implement an environment setting or anything else to set the client name? Mounting /etc/hostname as a persistent volume may work but setting it during the container creation could be an option, if I'm understanding how it works correctly. 
For instance, currently World Community Grid lists my docker client as "094976c6f248", which is not very user friendly. If I could set this that would be nice.

Edit: if it matters, I used a bridged network with the rpc port exposed instead of the host network.

**Comment by adamradocz** [comment]
My Docker is running on an Ubuntu Server, and I use the host network option as the documentation says, and my boinc is recognised correctly as the name of the PC.

**Comment by marius311** [comment]
You can always run with `docker run --hostname HOSTNAME` to set the hostname at container creation too.

**Comment by LiamAkkerman** [comment]
thank you! I didn't know that was part of docker itself, I thought it had be be implemented. World Community Grid now shows a usable name.
