### ISSUE TITLE
Streamline readme

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc-client-docker#2]
I wonder if the README can't be streamlined even a bit further. I get the sense when people arrive on a Docker container repo, they basically just want to immediately be presented with the one single `docker run ...` command so they can copy/paste it and get the app running, without too much thinking required or any other distractions.

Here they're presented with a choice between host/bridge networking which they may not know what that means, as well a docker compose option which again they may now know exactly.

Instead, I'd propose the top of the page lists one of the commands for host/bridge, and then even follows up with a screen shot something like this:
![image](https://user-images.githubusercontent.com/1510968/36479350-a0db8784-1708-11e8-853d-31d232c5a0e4.png)
as well as possibly a non-GUI command for accessing the client (i.e. via `boinccmd`) to make really clear what needs to be done afterwards to connect a client. 

In terms of host/bridge, do you think we need to present both? Have you found cases where one works but the other doesn't? I'd just go with bridge which is "default" but I'm open to suggestions. 

I can take a stab at creating a PR if you're ok with this idea.

**Comment by adamradocz** [comment]
I agree with all the things. And no, I didn't see any case when the bridge mode worked but the host didn't.

**Comment by adamradocz** [comment]
Only one thing. When I moved from docker to docker compose, I really liked when I could use a compose template, even tho I can write myself. Shouldn't we keep it somewhere?
