### ISSUE TITLE
With version 7.10.2 the default working directory changed to /var/lib/boinc

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc-client-docker#21]
With the latest BOINC 7.10.2 [on Linux the default working directory changed to](https://boinc.berkeley.edu/wiki/Release_Notes_for_BOINC_7.10) `/var/lib/boinc` from `/var/lab/boinc-client`
Should we modify our code and the readme to use the new standard?

**Comment by sunk818** [comment]
Less confusion if you follow the defaults of the version running inside docker. I noticed latest boinc docker is 7.12

```
$ sudo docker logs -f boinc
26-Oct-2018 17:51:53 [---] Starting BOINC client version 7.12.0 for x86_64-pc-linux-gnu
```
