### ISSUE TITLE
[Docker cloud] Wrong build order

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc-client-docker#24]
The automated build on Docker Cloud starts with the OpcenCl version not the master.

<img width="824" alt="docker cloud build order" src="https://user-images.githubusercontent.com/16503773/41678247-da1718e0-74ca-11e8-862c-7ca58f41e650.PNG">

**Comment by marius311** [comment]
The order they build on Cloud doesn't matter, the https://github.com/BOINC/boinc-client-docker/blob/master/hooks/build file makes it so each individual build builds the base image first. Its redundant, but the best we've got until they let us specify dependencies on Cloud.
