### ISSUE TITLE
What is the docker equivalent to boinc restart?

### ISSUE THREAD

**Issue by sunk818** [BOINC/boinc-client-docker#28]
In Ubuntu 16.0.4 LTS, I use this command to restart BOINC: **sudo service boinc-client restart**

What is the docker equivalent?

**Comment by adamradocz** [comment]
[docker restart [OPTIONS] CONTAINER [CONTAINER...]](https://docs.docker.com/engine/reference/commandline/restart/)

**Comment by sunk818** [comment]
Was trying to get it to work but the benchmark never happened and no downloads. I guess I should have tried skipping benchmark

**Comment by adamradocz** [comment]
The benchmark shows empty results for some reason, but the crunching works anyway.
