### ISSUE TITLE
Get VBox working

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc-client-docker#3]
Would be great to eventually have VBox working for projects with VBox apps. I played around with something like this a while back but never succeeded. https://github.com/laurent-malvert/docker-boinc#virtualbox seems like they may have something working, worth investigating maybe.

**Comment by adamradocz** [comment]
Can you tell me a vbox based project for testing?

**Comment by davidpanderson** [comment]
I don't understand.  When do things not work now?

**Comment by marius311** [comment]
@davidpanderson I meant get VBox working inside this Dockerized client container, which currently does not have VBox installed in it. 

@adamradocz I think the easiest thing would be to spin up a server using boinc-server-docker and since that comes with boinc2docker pre-installed, you can immediately submit VBox-based jobs with something like `bin/boinc2docker_create_work.py python:alpine python -c "print('Hello BOINC')"` (see also the readme / project cookbook for boinc-server-docker). If you wanted a real-life project with VBox apps, I suppose I'm partial to www.cosmologyathome.org :)
