### ISSUE TITLE
How do we edit global_prefs.xml?

### ISSUE THREAD

**Issue by sunk818** [BOINC/boinc-client-docker#48]
I have 2 vCPUs on a Google optimized container. the max disk usage was 0.38GB. After I changed the -v to my home directory instead (e.g. `/home/me:/var/lib/boinc-client`), I was able to get 2.85GB. BOINC by default uses 50% of available space?

How can I edit global_prefs.xml or add a global_prefs_override.xml? I think this is global_prefs.xm is in `/var/lib/boinc-client` (although this changed in Ubuntu 18?)?

**Comment by adamradocz** [comment]
You can configure the client by connecting to it with a manager.

**Comment by sunk818** [comment]
I see the `/var/lib/boinc-client` files are mapped outside of the docker container? So, I can edit it outside of docker.
