### ISSUE TITLE
Plans to add ARM based Docker image

### ISSUE THREAD

**Issue by afritzler** [BOINC/boinc-client-docker#50]
Hi,
are there any plans to add support for an ARM based Docker image?
Regards,
Andreas

**Comment by adamradocz** [comment]
Which type of ARM fo you want? ARMv8 64-bit or ARMv7 32-bit?

**Comment by afritzler** [comment]
ARMv8 would be good.

**Comment by afritzler** [comment]
I just saw that you added the Dockerfile already with e94297a599958df1be0eb5680b2ab2a22e219ffd . Thanks a lot!

**Comment by adamradocz** [comment]
Yes, but there is a catch. Docker cloud can't build the ARM based images, so if you want to use it you have to build it.
- Clone the GitHub repo.
- cd in the repo.
- docker build -t boinc/client:arm64v8 -f Docker file.arm64v8 .

**Comment by AenBleidd** [comment]
@afritzler, you can take a look at the official list of projects and their supported platforms here:
https://boinc.berkeley.edu/projects.php

**Comment by afritzler** [comment]
That was exactly what I was looking for! Thanks a lot for the link!

**Comment by adamradocz** [comment]
@afritzler that'd be nice. @marius311 could you add @afritzler upload permission on Docker cloud?

**Comment by RichardHaselgrove** [comment]
If you look at the file `all_projects_list.xml` (updated every 14 days in the data directory of any running BOINC client), the application plan class names are listed and give an insight into the various hardware and software versions supported. Einstein and SETI probably have the most comprehensive lists.

**Comment by afritzler** [comment]
Ok, so I did a quick smoke test on a Raspberry Pi 3. Works like a charm with SETI! Unfortunately I am running HypriotOS for armv7 on this puppy so I had to change the base image to `arm32v7/ubuntu`. Will flash the device with an armv8 OS.

Thank you guys a lot for the support!

**Comment by afritzler** [comment]
I created a PR #51 to also add support for arm32v7 based devices.

**Comment by marius311** [comment]
> @marius311 could you add @afritzler upload permission on Docker cloud?

@afritzler what's your Docker hub username?

**Comment by afritzler** [comment]
Same as my github user: https://hub.docker.com/u/afritzler/

**Comment by marius311** [comment]
K I think what I just did gave you push access to boinc/client. Let me know if it didn't. Use responsibly :)

**Comment by afritzler** [comment]
Thx & of course :-)
