### ISSUE TITLE
--net=host vs EXPOSE

### ISSUE THREAD

**Issue by Mausy5043** [BOINC/boinc-client-docker#56]
Why is the container using `--net=host` while it also `EXPOSE`s port 31416? 

I am hesitant to allow the container full access to the host's network stack. I see no reason for doing this.

What problems do I need to look out for if I would use the option `-p 31416:31416` and remove the option `--net=host`? It seems to work just fine. 😕

**Comment by adamradocz** [comment]
It's the same, it will work with the `-p 31416:31416` just fine. The `--net=host` just simpler.

**Comment by Mausy5043** [comment]
If they are equivalent I'd recommend to use the `-p` option as the `--net=host` option may pose a security risk to users.

**Comment by adamradocz** [comment]
The `host` option remove network isolation between the container and the Docker host, and use the host’s networking directly. It's basically the same as installing the BOINC on the host, there's no extra security risk, and there aren't any extra open ports.

**Comment by Utopiah** [comment]
Even though is might be equivalent in terms of security it is worrisome for people who are unfamiliar with the project. This is why I ended up here, looking for a possible `-p` alternative.
