### ISSUE TITLE
Why isn't arm64 version listed in Docker hub?

### ISSUE THREAD

**Issue by meetyg** [BOINC/boinc-client-docker#61]
I didn't even know a 64 bit version for ARM existed untill just browsing this repo.
If there is an arm64 image, I think it should be added to Docker hub and readme too.
Thanks you for mainting these Docker images, there are very helpfull !

**Comment by meetyg** [comment]
Just an update, reading some other issues I understood that Docker hub can build these ARM images. So @afritzler pushed the arm32v7 images, but not the arm64v8.
I have successfully built the arm64v8 image on my Rock64 and its working nicely.
Still we should have this listed on DockerHub, to save others from having to build.
I'm willing to do it if @afritzler  is too busy for it.

**Comment by afritzler** [comment]
Unfortunately I currently don't have a 64bit OS running on ARM to test it. If you can confirm that it works - that is awesome. @marius311 can give you push rights to Docker hub.

**Comment by meetyg** [comment]
Yes, I have it up and running (crunching Boinc) on my Pine Rock64, with 64bit Debian OS on it.

**Comment by adamradocz** [comment]
An optimized version is always faster. The 64bit processor has to convert the 32bit values to 64bit which is an extra overhead. Not much, but still... :)
BTW, can you see what values are shown when you run a benchmark?

**Comment by meetyg** [comment]
I can't see benchmark results, not in 32bit version and not in 64bit. I don't know if has to do with the fact that we are running in Docker, or that we are running on ARM architecture. The benchmark shows blank lines in the log, as mentioned in issue #9 
Any ideas why this happens? (Same behaviour on my Raspberry Pis, all running Boinc in docker).

**Comment by adamradocz** [comment]
I've no idea, I was aware of the issue. I was curious that maybe it shows something in ARM.

**Comment by meetyg** [comment]
So I guess its a Docker problem. 
Maybe we are missing a dependecy or something.

**Comment by adamradocz** [comment]
apt should install any necessary dependencies.

**Comment by adamradocz** [comment]
@meetyg the base image is switched to Alpine Linux so our image is smaller now. You can build a new image and try out.

**Comment by meetyg** [comment]
Ok, so I built the new Alpine image for arm64.
It seems that tasks that were already running, continue to run.
But unfortunately, I am unable to get new tasks. It seems that the Alpine's musl lib is not supported. 
Here is what I get in the event log:
```
15/05/2019 22:44:27 | TN-Grid Platform | Message from server: This project doesn't support computers of type aarch64-alpine-linux-musl
15/05/2019 22:44:34 | Universe@Home | Message from server: This project doesn't support computers of type aarch64-alpine-linux-musl
```
These two projects worked fine on the previous arm64 image (based on arm64 Ubuntu)

**Comment by adamradocz** [comment]
Hmm, thanks for the feedback.
It seems I need to switch back to Ubuntu then. Unfortunately, it is 10X bigger.

**Comment by meetyg** [comment]
Now I recall that I had a similar problem when I tried to run Boinc (not in Docker) on a Raspberry Pi with Alpine linux running on it (don't remember if it was 32 or 64 bit).
But maybe we still have some hope...  Maybe we can "fool" the system to think that we have some other architecture? 
As I mentioned, it seems like tasks that were already running, continued to run. I didn't check to see what happens when they end and try to report (takes hours for a task to complete).
So maybe the Boinc servers are just reject the Alpine arch because they don't Identify it.
Any ideas how to do this?

**Comment by marius311** [comment]
> It seems I need to switch back to Ubuntu then

**Comment by adamradocz** [comment]
I did the change in the #63 PR. Everything is working as it should be. I left the alpine base image in the repository though, but the Ubuntu is the default base image now.

**Comment by meetyg** [comment]
I have rebuilt the Arm64 image.
Its currently running great on three different 64 bit Arm devices: Pi 3, Rock64 and a NanoPi Fire3. Checked with Universe@Home, an TN-Grid, both getting nice results.
Could I please get permissions (from @marius311 ?) to push this Docker hub?

**Comment by afritzler** [comment]
Out of curiosity: what 64bit OS are you using on your RPi3?

**Comment by meetyg** [comment]
I'm using Ubuntu's 64 bit image for Raspberry Pi 3:
https://wiki.ubuntu.com/ARM/RaspberryPi

Specifically:
ubuntu-18.04.2-preinstalled-server-arm64+raspi3.img.xz

It a bit large (4GB), but it works pretty well.

**Comment by adamradocz** [comment]
If you manage multiple clients, I created a rudimental, but working version of a [web-based Boinc Manager](https://github.com/adamradocz/boinc-manager), which runs on Docker. If you wanna try, go and check out.

**Comment by meetyg** [comment]
Sounds 😎 I surely will give it a try soon!

**Comment by SSCCpicocluster** [comment]
Hello, my team and I are working on clustering ~300 raspberry pi 3's like a school project and we're currently hitting a roadblock with the image docker and BOINC are pushing out. We believe that the issue is being caused due to the ARM 64 image (or possible lack thereof ) for  Raspbian. Is there a repository for the correct image version, or is it recommended to switch to another node operating system?

**Comment by adamradocz** [comment]
@marius311 Can we resolve this issue?

**Comment by marius311** [comment]
> Can we resolve this issue?

**Comment by adamradocz** [comment]
@meetyg needs uploading permission.

**Comment by marius311** [comment]
Oh I see now above, sorry. @meetyg whats your Docker username? I can add you (FWIW I think you have permission to add people too @adamradocz)

**Comment by meetyg** [comment]
My username is: meetyg
https://hub.docker.com/u/meetyg

**Comment by adamradocz** [comment]
Oh, I didn't know that.

**Comment by meetyg** [comment]
Sorry for the late response (been busy lately...)
Anyways, I'm rebuilding the latest version, and will push to Dockerhub.
I'll have you guys updated :smile:

**Comment by meetyg** [comment]
Done :+1: 
You can now pull the image: `docker pull boinc/client:arm64v8`
I will open a pull request to update the readme with this tag.

I ran a basic sanity test on this image after rebuilding it, but haven't had the time to change my currently running instance with the new one. 
So @SSCCpicocluster  if you have any problems, let me know.
The image was built on an RPI 3 B+ running 64bit Ubuntu, as I have mentioned before.
Enjoy!

**Comment by adamradocz** [comment]
Thanks.
