### ISSUE TITLE
Change timezone

### ISSUE THREAD

**Issue by distahl** [BOINC/boinc-client-docker#67]
Hi,

How can I change timezone in the docker image?
I've tried already -e `"TZ=Europe/Berlin"` and `-v /etc/timezone:/etc/timezone:ro`

But `date` always shows the same time. Even if I set to "America/Montreal".

```
Mon Sep 30 07:15:14 Europe 2019
Mon Sep 30 07:15:14 America 2019
```

And boinc always is saying:
`Local time is UTC +0 hours`

**Comment by adamradocz** [comment]
`tzdata` has been added to the image, so the `-e TZ=Europe/Berlin` should work now. 1-2 hours and the images will be rebuilt.
