### ISSUE TITLE
Process usage less than X percent doesn't work with docker

### ISSUE THREAD

**Issue by superflyxxi** [BOINC/boinc-client-docker#69]
When running docker boinc, it doesn't honor `While processor usage is less than ___ percent` setting. This may be due to how the client is identifying processor usage. Within a container, if you were to run top you'd only see the processor usage of the processes within the container. You do not see the host processes at all. So from a container perspective, it seems like  no other process is running except for your own. This is by design of docker.

I'm not sure what can be done about this, but logging this issue to track how to do this and finally fix it. At the very least update the documentation.

**Comment by superflyxxi** [comment]
By using `--pid=host` in the dock run command, the container can view all processes on the host. This allows for CPU percentage and exclusive apps to be honored

**Comment by adamradocz** [comment]
Thanks. Would you like to update the documentation and making a PR?
