### ISSUE TITLE
Invalid link to image at docker hub

### ISSUE THREAD

**Issue by Heaven31415** [BOINC/boinc-client-docker#72]
If you look at https://hub.docker.com/r/boinc/client under **usage** section you will find a broken link to this image: https://hub.docker.com/r/boinc/manager_connect.png

![image](https://user-images.githubusercontent.com/16988850/70918205-08af4280-201f-11ea-9207-279c113164c7.png)

**Comment by adamradocz** [comment]
Because the links are optimized for GitHub and the DockerHub doesn't handle it well.
