### ISSUE TITLE
Confusing documentation, help?

### ISSUE THREAD

**Issue by mcandre** [BOINC/boinc-client-docker#74]
Hi,

I want to run BOINC in Docker and contribute to major Rosetta@Home efforts. But I am having trouble understanding the right syntax for this. Where do I input my BOINC username and password?

It seems that this Docker image is only one component of the overall BOINC desktop system. Can we get an all-in-one image for easy deployment by Kubernetes admins?

**Comment by tristanolive** [comment]
I'm pretty sure the BOINC client runs when you launch the Docker container from the image. Once it's running, you can attach to Rosetta like this:

docker exec -it [container] boinccmd --project_attach https://boinc.bakerlab.org/rosetta/ [account_key]

Note that it uses your Rosetta account key, not name and password. This key can be found by logging into your account at the Rosetta website. This would only need to be done once to set up the container, then subsequent runs should work as expected.

**Comment by adamradocz** [comment]
Or connect to the client with the BOINC manager and configure that way.

**Comment by adamradocz** [comment]
If you need help, just reopen the issue.
