### ISSUE TITLE
BOINC uses ~40% "kernel" CPU usage but only ~15% "user" CPU usage.

### ISSUE THREAD

**Issue by garethrandall** [BOINC/boinc-client-docker#78]
I have been running Boinc with World Community Grid for several months now on a cloud-hosted machine, using the latest `Dockerfile.base-ubuntu`.

I'm wondering if anyone else running Boinc in a Docker container sees their running process consume an enormous amount of kernel CPU time ("39.3 sy" below) while the user mode calculations only get a small fraction of this ("12.8 ni" below). This happens both with the latest github repository revision (commit d0311b4064db1139c3ac4f32e84529461e30f86c) and also a revision from late 2019.

Expected result: The ni value should be close to 100% and the sy value should be close to 0%.

Is this a Docker bug, or are there options in Docker to avoid this happening? I have run `strace` on the wcg process but it is only making a few system calls a second. Apologies if this issue is "off topic", and thank you for any suggestions.

```
%Cpu(s):  0.0 us, 39.3 sy, 12.8 ni, 45.3 id,  2.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2033684 total,    76368 free,  1886216 used,    71100 buff/cache
KiB Swap:  2097148 total,  1851700 free,   245448 used.    34484 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                         
 88697 root      39  19   67796  14140   1488 S 51.7  0.7   7:05.05 wcgrid_mcm1_map
```

```
# docker --version
Docker version 19.03.8, build afacb8b7f0
# uname -a
Linux nagios 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
```

**Comment by adamradocz** [comment]
Honesty, I have no idea. What do you use for this stat? I'll check my NAS.

**Comment by garethrandall** [comment]
Thanks for the reply. This was when running the standard "top" command.

**Comment by garethrandall** [comment]
Maybe there's something wrong with the Boinc process itself. The output of `strace -p 104121` shows the following repeated about every 2-3 seconds, but the `times` lines occur around 750-850 times each repeat. Perhaps this repeating `times` call is causing the high kernel load?

```
times({tms_utime=8876, tms_stime=22608, tms_cutime=0, tms_cstime=0}) = 2228470293
times({tms_utime=8876, tms_stime=22608, tms_cutime=0, tms_cstime=0}) = 2228470293
times({tms_utime=8876, tms_stime=22608, tms_cutime=0, tms_cstime=0}) = 2228470293
times({tms_utime=8876, tms_stime=22608, tms_cutime=0, tms_cstime=0}) = 2228470293
times({tms_utime=8876, tms_stime=22608, tms_cutime=0, tms_cstime=0}) = 2228470293
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
getrusage(RUSAGE_SELF, {ru_utime={tv_sec=88, tv_usec=760000}, ru_stime={tv_sec=226, tv_usec=88000}, ...}) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [ALRM], 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [ALRM], NULL, 8) = 0
nanosleep({tv_sec=1, tv_nsec=0}, ^Cstrace: Process 104121 detached
 <detached ...>
```

**Comment by adamradocz** [comment]
My stats seem to OK.
```
top - 07:47:38 up 14:34,  1 user,  load average: 2.89, 3.10, 3.10
Tasks: 253 total,   3 running, 250 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.7 us,  2.5 sy, 49.3 ni, 35.8 id,  1.9 wa,  0.0 hi,  1.7 si,  0.0 st
MiB Mem :   3594.0 total,    163.2 free,   3023.3 used,    407.5 buff/cache
MiB Swap:   3944.0 total,   3129.5 free,    814.5 used.    302.4 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
17311 adam      39  19 1345184   1.1g  16532 R 100.0  31.9  19:17.94 rosetta_4.08_x8
30533 adam      39  19 1423684   1.2g  22756 R 100.0  33.4  92:59.70 rosetta_4.08_x8
  911 root      20   0 2264392  24272   2756 S   1.6   0.7   4:32.44 dockerd
 1043 root      20   0 2192004  10008   2360 S   0.8   0.3   2:34.98 docker-containe
 1437 root      20   0   10216   2640   1524 S   0.8   0.1   1:35.74 docker-containe
```

**Comment by garethrandall** [comment]
Thanks for checking.

I'm going to close this issue because it doesn't seem that it's directly related to  "BOINC/boinc-client-docker". Thanks for your help.
