### ISSUE TITLE
Client not restarting after boot

### ISSUE THREAD

**Issue by DanielAlcon** [BOINC/boinc-client-docker#80]
I followed the instructions to setup docker boinc client, but after restarting the computer I can connect to the container despite trying to restart it.

The boinc manager says it's disconnected

**Comment by adamradocz** [comment]
The container is running?

**Comment by DanielAlcon** [comment]
Everything is working now, I removed everything and reinstalled and now I don't have any problem except that I can't use boinc client to connect after reboot, only on first start. But I'm using boinccmd to manage everything in all my computers right now

**Comment by adamradocz** [comment]
For some reason `--allow_remote_gui_rpc` not working correctly.
In the `cc_config.xml` under the `<options>` section set the `<allow_remote_gui_rpc>` to `1`
