### ISSUE TITLE
Switching to official Ubuntu base image for ARM

### ISSUE THREAD

**Issue by afritzler** [BOINC/boinc-client-docker#83]
It might be a good idea to switch to the official `ubuntu:rolling` base image[0] as it now supports both 32 and 64bit ARM. Wdyt?

[0] https://hub.docker.com/_/ubuntu/?tab=tags

**Comment by adamradocz** [comment]
We use the `20.04` image which is the same as the `rolling`.

**Comment by afritzler** [comment]
Sorry for the confusing title. I meant the images for arm.

**Comment by adamradocz** [comment]
For arm we use the rolling image, and I don't find any information about the multiarc image.

**Comment by adamradocz** [comment]
If you want, you can create a PR.
