### ISSUE TITLE
Wishlist of boinc-client-docker for newly coming Windows Subsystem of Linux 2.0

### ISSUE THREAD

**Issue by leeee-me** [BOINC/boinc-client-docker#85]
Recently I am studying the newly pre-release (or previewed) of Win 10 WSL 2 with transparently CUDA support on top of underlying DirectX GPU hypervisor... for personal interests, to see if any BOINC GPU-based projects (especially for nVidia CUDA) can run on top of WSL2.

Currently, this preview is based on CUDA 11.1 with nVidia customized docker-ce engine and cuda cli/api

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

May I expect that boinc-client-docker can be adapted for this configuration soon?

Thank you

**Comment by adamradocz** [comment]
I think there's no point installing docker on WSL. And maybe boinc support WSL by default?
