### ISSUE TITLE
Warn about VirtualBox version mismatches between guest and host

### ISSUE THREAD

**Issue by lunik1** [BOINC/boinc-client-docker#86]
While trying to use the Virtualbox-savvy version of this image I encountered this error when running VBoxHeadless:
```
Error -1912 in supR3HardenedMainInitRuntime!
```
which is caused by [a version mismatch between the host's kernel modules and guest's VirtualBox version](https://www.virtualbox.org/ticket/6337). If you are using Ubuntu 18.04 you shouldn't encounter this issue as the version in the repos should match, but other host distros may encounter problems. My host had VirtualBox 6!

I think a warning should be placed in the documentation that these versions must match. Although in my case it was a major version difference, I confirmed via the VirtualBox IRC on Freenode that the versions must by identical, i.e. the same major.minor.patch.

**Comment by adamradocz** [comment]
Thanks!
