### ISSUE TITLE
Blank benchmark result

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc-client-docker#9]
When you run the CPU benchmarks, in the Event log the scores are blank. I assume the ubuntu image doesn't contain the necessary package which is required for benchmarking, but I don't know what's the requirement for that.

The wrong result on the docker:
<img width="434" alt="wrong-benchmark-result" src="https://user-images.githubusercontent.com/16503773/37224778-bfe33950-23d4-11e8-8c03-d47b7d83580a.PNG">

The correct one on my local pc:
<img width="437" alt="correct-benchmark-result" src="https://user-images.githubusercontent.com/16503773/37224807-d53cf7b4-23d4-11e8-9438-3d7bf5c13c4b.PNG">

**Comment by adamradocz** [comment]
It works again.

**Comment by latenightdef** [comment]
2023 update: make sure you don't forget `--pid=host` in the docker run commend or benchmark output will be blank
