### ISSUE TITLE
add BOINC website credentials 

### ISSUE THREAD

**Issue by guillaume130679** [BOINC/boinc-client-docker#90]
Hello, 

This is not exactly an issue I am reporting here but I was wondering if there was any way I could include my BOINC credentials directly into docker containers config? 

At the moment, if I run a deployment with several containers I need to add my credentials in every single one of them before they start processing data.

Maybe that would be a feature to add?

**Comment by adamradocz** [comment]
You can use the [command line](https://boinc.berkeley.edu/wiki/Boinccmd_tool) argument to add the credentials.
