### ISSUE TITLE
Including a web client directly or providing a docker-compose example

### ISSUE THREAD

**Issue by Utopiah** [BOINC/boinc-client-docker#91]
As I imagine most Docker users will do it on headless server and coming from Archive-Warrior, providing such an option would be great.

Including directly a client, e.g https://github.com/Raffy23/boinc-webmanager , might be too much work but integrating both via a docker-compose example would limit to changing only the documentation rather than adding a dependency.

**Comment by adamradocz** [comment]
Sorry, I don't exactly understand what you mean. You want a docker-compose example with boinc and boinc-webmanager?

**Comment by Utopiah** [comment]
Yes. I'm not familiar with BOINC so my comment is naive. I installed the client and it worked well but I was surprised to have to have the GUI manager to connect to it. I imagine the process was historical, namely that BOINC was created before Docker rise to popularity. Most services nowadays that come with a Docker image usually have a web interface so I was expecting BOINC to have that too. Consequently I'm wondering what's the best compromise to make this image easier to manage for newcomers. I imagine it a good compromise could be a docker-compose example.

**Comment by adamradocz** [comment]
Unfortunately, the boinc-webmanager is not an official project. And the idea is that you run the boinc clinet docker in a headless server and you connect to that client with the boinc manager from your PC.

**Comment by Utopiah** [comment]
Yes I understand the idea. I did that and it works. I'm comparing to my prior Archive-Warrior experience and to be honest a last of Docker project featuring web-based interface. That being said again I don't know BOINC well enough to have a strong opinion so maybe the native GUI BOINC manager is the only proper or complete way to handle the client. If that's the case feel free to close the issue.

**Comment by adamradocz** [comment]
Having an official web GUI is a good idea. You should open an issue about that in the [BOINC](https://github.com/BOINC/boinc) repo. When it's done, I'll add it to this project.
