### ISSUE TITLE
For virtualbox -ed boinc container, it seems not install proper ext pack 

### ISSUE THREAD

**Issue by leeee-me** [BOINC/boinc-client-docker#93]
I tried this container to crunch tasks of Rosetta @ Home, which it now needs virtualbox to run its python computational box.
It needs to run headless virtualbox instances for each tasks...
The task failed immediately which error log shows that virtualbox started and then went dead.

I made a guess that it is forgotten to install headless extpack.
For example, I googled and provided a simple article to tell how to install extpack by command line (vboxmanage decided correct extpack version and URL to download)
https://techviewleo.com/install-virtualbox-extension-pack-using-vboxmanage/

Please update your docker file and/or image to add this missing portion

**Comment by adamradocz** [comment]
The host and the docker has to have the same virtualbox installed. Can you confirm that?

**Comment by leeee-me** [comment]
I confirmed that virtualbox installed on both docker and host are different. However, I tried to apt upgrade inside docker and then both virtualbox-es are matched as the same version. But the "vboxmanage list extpacks" in docker does not show the same extpack as the ones installed in the host.

Since extpack is mandatory for specific BOINC projects, I might suggest to add extpack download and installation in Dockfile.

Is this reasonable? thanks for advice

**Comment by adamradocz** [comment]
Can you make a PR for that?

**Comment by leeee-me** [comment]
It can be quite simple, just modify Dockerfile.virtualbox


# Install
RUN apt-get update && apt-get install -y --no-install-recommends \
# Install VirtualBox
    virtualbox && \
    echo virtualbox-ext-pack virtualbox-ext-pack/license select true | debconf-set-selections && \
    apt-get install -y --no-install-recommends virtualbox-ext-pack && \
# Cleaning up
    rm -rf /var/lib/apt/lists/*

**Comment by adamradocz** [comment]
Pushed the updated image to Docker HUB. Can you check it, please?

**Comment by leeee-me** [comment]
Tried to pull it and build boinc/client:virtualbox locally, and then run it. It looks perfectly to work
