### ISSUE TITLE
Some projects might require additional packages installed

### ISSUE THREAD

**Issue by pataquets** [BOINC/boinc-client-docker#95]
Case in point: LHC@Home:
Task output log:
```
<core_client_version>7.16.17</core_client_version>
<![CDATA[
<message>
process exited with code 195 (0xc3, -61)</message>
<stderr_txt>
15:46:57 (14662): wrapper (7.15.26016): starting
15:46:57 (14662): wrapper (7.15.26016): starting
15:46:57 (14662): wrapper: running ../../projects/lhcathome.cern.ch_lhcathome/cranky-0.0.32 ()
15:46:57 UTC +00:00 2022-05-08: cranky-0.0.32: [INFO] Detected Theory App
15:46:57 UTC +00:00 2022-05-08: cranky-0.0.32: [INFO] Checking CVMFS.
15:46:57 UTC +00:00 2022-05-08: cranky-0.0.32: [ERROR] 'which' could not locate the command 'cvmfs_config'.
15:46:58 (14662): cranky exited; CPU time 0.011948
15:46:58 (14662): app exit status: 0xce
15:46:58 (14662): called boinc_finish(195)

</stderr_txt>
]]>
```
I'm not sure what would be needed to do.
* Just mentioning it in the readme
* Add them to this image. Quite an effort, since it had to be done and kept updated for each possible project, which is hard.
* If those projects use/recommend Docker for easier deployment, leave it up, but maybe warn them about it (or encourage them to publish an image derived from this, but with those requirements installed).

**Comment by adamradocz** [comment]
Have you tried contacting them?

I think it's the project owner's responsibility to install all the necessary packages to be able to run the tasks. I can't monitor all the available BOINC projects just to make sure they did everything right.

**Comment by pataquets** [comment]
Thanks for the prompt response, @adamradocz.
I have not contacted them, indeed. Understandably, adding the packages to this image is the hardest approach, due to having to keep track of every required package by every supported project, which is absurdly hard.
I've just tried adding the reqd packages in an image of my own, but did not work, so I've just skipped the project.
I was not requesting the packages, nor expecting to be added/keept track of on this repo, but just pointing it out, so far (edited OP).
IMO, the ideal approach would be every project to publish their own Docker image derived from this one, but with the required additions.

**Comment by alee18x** [comment]
To run LHC@Home, it needs: 
1). CVMFS (https://twiki.cern.ch/twiki/bin/view/AtlasComputing/Cvmfs21) to supply LHC distributed data pool
2). Go-lang and run a specific app called Singularity (https://github.com/apptainer/singularity)
3). Virtualbox VMM

And LHC @ Home is running often with a very heavy loading which is not respectful BOINC's global preference of CPU usage.

**Comment by pataquets** [comment]
@alee18x Thank you very much for the instructions. I've never run Vb on Docker. I even doubt it can work. Anyway I'll not take that route due to complexity. Finding another project is easier. :smile:
@adamradocz Worth mentioning something in the readme, at least? To avoid ppl the headscratching for projects not working. I was not asking necessarily for neither support nor a fix, since my first proposed action was to just mention it. My apologies if that was it looked like.
